<!DOCTYPE HTML>
<html>

<head>
         <meta charset="utf-8">
         <link href="../css/bootstrap.min.css" rel="stylesheet">
         <link href="../css/bootstrap-theme.min.css" rel="stylesheet">
         <link href="../css/custom.css" rel="stylesheet">
         <link href="../js/bootstrap.min.js" rel="stylesheet">
         <title>Max & Keni Art Page</title>
         </head>

         <header>

         <div class="page-header">
         	<h1><p align="center">MAX & KENI</p></h1>
         	</div>

         	<?php require("menu.phtml"); ?>

         	</header>

         	<body>
         	

  <div class="row text-center">
  <br><br>
 
<h2>Website Devlopped by Maxime LAILVAUX and Quentin Mazard<br> Student at the engineering school ESIEA contact us as lailvaux[at]et.esiea.fr
</h2>
</div>

 
 
 
  </body>
</html>