<!DOCTYPE HTML>
<html>

<head>
         <meta charset="utf-8">
         <link href="../css/bootstrap.min.css" rel="stylesheet">
         <link href="../css/bootstrap-theme.min.css" rel="stylesheet">
         <link href="../css/custom.css" rel="stylesheet">
         <link href="../js/bootstrap.min.js" rel="stylesheet">
         <title>Max & Keni Art Page</title>
         </head>

         <header>

         <div class="page-header">
         	<h1><p align="center">MAX & KENI</p></h1>
         	</div>

         	<?php require("menu.phtml"); ?>

         	</header>

         	<body>

 <div class="container">
					<form action=/create method="post" enctype="multipart/form-data">

					<div class="row">
					<h1 class="titre">Add a works of art</h1>
					</div>

					<div class="form-group">
					<label for="author">Author</label>
					<input type="text" class="form-control" id="author" name="author" placeholder="Author" required>
					</div>

					<div class="form-group">
					<label for="description">Description</label>
					<input type="text" class="form-control" id="description" name="description" placeholder="Description">
					</div>

					<div class="form-group">
					<label for="title">Title</label>
					<input type="text" class="form-control" id="title" name="title" placeholder="Title" required >
					</div>

					<div class="form-group">
					<label for="date_creation">Date of creation</label>
					<input type="text" class="form-control" id="date_creation" name="date_creation" placeholder="Date of creation">
					</div>

					<div class="form-group">
					<label for="place">Place</label>
					<input type="text" class="form-control" id="place" name="place" placeholder="Place" required>
					</div>

					<div class="form-group">
					<label for="place_creation">Place of creation</label>
					<input type="text" class="form-control" id="place_creation" name="place_creation" placeholder="Place of creation">
					</div>


    <label class="control-label">Select image</label>

					<input type="file" name="imgFile" required>
    
					
					
					
					
					<p id="buttons">
					  <input type="submit" name="btn_upload" value="Add" class="btn btn-success center-block btn-md" /> 



					  
					  
					</p>
					</form>


					 </div>
     
 
  </body>
</html>