<!DOCTYPE HTML>
<html>



<head>
         <meta charset="utf-8">
         <link href="../css/bootstrap.min.css" rel="stylesheet">
         <link href="../css/bootstrap-theme.min.css" rel="stylesheet">
         <link href="../css/custom.css" rel="stylesheet">
         <link href="../js/bootstrap.min.js" rel="stylesheet">
         <title>Max & Keni Art Page</title>
         </head>

         <header>

         <div class="page-header">
            <h1><p align="center">MAX & KENI</p></h1>
            </div>

            <?php require("menu.phtml"); ?>

            </header>

            <body>
 

                
                    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">All works of art
                    
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->
        <div class="row">
        <?php foreach ($datasites as $datasite) {?>









            <div class="col-md-4 ">
                <a href="/paint/<?= $datasite->id ?>">
                  <div class="image" style="background-image:url(../Images/<?= $datasite->img ?>)"></div>
                </a>
                <h3>
                
                    <p>Name : <?= $datasite->title ?></p>
                </h3>
                <p>Author : <?= $datasite->author ?></p>
                <p>Place : <?= $datasite->place ?></p>
                </br>
                </br>
                </br>

                    
                    
           
             
      

            </div>
                 <?php } ?>
        </div>




        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; MAX&KENNY2016</p>
                </div>
            </div>
        </footer>
    </div>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
          
            </div>
      </div>
</nav>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
  </body>
</html>