<!DOCTYPE HTML>
<html>



<head>
         <meta charset="utf-8">
         <link href="../css/bootstrap.min.css" rel="stylesheet">
         <link href="../css/bootstrap-theme.min.css" rel="stylesheet">
         <link href="../css/custom.css" rel="stylesheet">
         <link href="../js/bootstrap.min.js" rel="stylesheet">
         <title>Max & Keni Art Page</title>
         </head>

         <header>

         <div class="page-header">
         	<h1><p align="center">MAX & KENI</p></h1>
         	</div>

         	<?php require("menu.phtml"); ?>

         	</header>

         	<body>
 
	  
<div class="container">
	  	

	  	<?php {?>
	      <img class="img-responsive center-block" src="../Images/<?= $datasite->img ?>" alt="">
	     
	     
	     

	                <p><label for="title">Title</label> : <?= $datasite->title ?></p>
	                <p><label for="author">Author</label> : <?= $datasite->author ?></p>
					<p><label for="date_creation">Date of creation</label> <?= $datasite->date_creation ?></p>	
					<p><label for="place">Place</label> : <?= $datasite->place ?></p>
					<p><label for="place_creation">Place of creation</label> : <?= $datasite->place_creation ?></p>
	                <p><label for="description">Description</label> : <?= $datasite->description ?></p>


	                <div class="row text-center">
	      <a href="/update/<?= $datasite->id ?>" class="btn btn-primary " role="button">Update</a>
	      <a href="/delete/<?= $datasite->id ?>"class="btn btn-danger " role="button">Delete</a>
	       
	       </div>

	    <?php } ?>

	


</div>


 
 
  </body>

      <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
</html>