<!DOCTYPE HTML>
<html>

<head>
         <meta charset="utf-8">
         <link href="../css/bootstrap.min.css" rel="stylesheet">
         <link href="../css/bootstrap-theme.min.css" rel="stylesheet">
         <link href="../css/custom.css" rel="stylesheet">
         <link href="../js/bootstrap.min.js" rel="stylesheet">
         <title>Max & Keni Art Page</title>
         </head>

         <header>

         <div class="page-header">
         	<h1><p align="center">MAX & KENI</p></h1>
         	</div>

         	<?php require("menu.phtml"); ?>

         	</header>

         	<body>
  <?php {?>
  
		<div id="menu">
					<form action="/update/<?= $datasite->id ?>" method="post" enctype="multipart/form-data">
					<p class="titre">General informations</p>




					<h1 class="titre">Update a works of art</h1>

					<div class="form-group">
					<label for="author">Author</label>
					<input type="text" class="form-control" name="author" id="author" value="<?= $datasite->author ?>">
					</div>

					<div class="form-group">
					<label for="description">Description</label>
					<input type="text" class="form-control" name="description" value="<?= $datasite->description ?>">
					</div>

					<div class="form-group">
					<label for="title">Title</label>
					<input type="text" class="form-control" name="title" value="<?= $datasite->title ?>">
					</div>

					<div class="form-group">
					<label for="date_creation">Date of creation</label>
					<input type="text" class="form-control" name="date_creation" value="<?= $datasite->date_creation ?>">
					</div>

					<div class="form-group">
					<label for="place">Place</label>
					<input type="text" class="form-control" name="place" value="<?= $datasite->place ?>">
					</div>

					<div class="form-group">
					<label for="place_creation">Place of creation</label>
					<input type="text" class="form-control" name="place_creation" value="<?= $datasite->place_creation ?>">
					</div>

				

					
										 						
															
					


							<?php } ?>	

					
					
					
					<p id="buttons">
					  <input type="submit" value="Add" />
					  
					  
					</p>
					</form>
        </div>
 
  </body>
</html>